#pragma once
#ifdef _WIN32  //for win32
#ifdef LIBGRAPHALGORITHM_EXPORTS
#define LIBGRAPHALGORITHM_PORT __declspec(dllexport)
#else
#define LIBGRAPHALGORITHM_PORT __declspec(dllimport)
#endif // LIBGRAPHALGORITHM_EXPORTS
#define LIBGRAPHALGORITHM_CALL __stdcall
#else  // otherwise
#define LIBGRAPHALGORITHM_PORT
#define LIBGRAPHALGORITHM_CALL
#endif  // _WIN32
#define LIBGRAPHALGORITHM_API LIBGRAPHALGORITHM_PORT LIBGRAPHALGORITHM_CALL
